version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Chore"
    labels:
      - "update"
      - "priority/low"
      - "size/xs"
    groups:
      testing:
        dependency-type: "development"
        patterns:
          - "xunit*"
          - "Microsoft.NET.Test.Sdk"
          - "coverlet.collector"
      natsu:
        dependency-type: "production"
        patterns:
          - "Roslynator.Analyzers"
          - "SkiaSharp*"
